### 1. Search Users
GET http://localhost:5273/api/admin/users 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NSIsImVtYWlsIjoiYWRtaW5AYWRtaW4xLmNvbSIsIm5hbWUiOiIiLCJqdGkiOiIxNGY3NmYzNy1hZmNiLTQ5YmQtODBjYi04NWFlMDE4YzdlZWQiLCJpYXQiOjE3NTQ4MjMwMjMsInBlcm1pc3Npb24iOlsiQ2FuUmVhZFBlcm1pc3Npb24iLCJDYW5DcmVhdGVQZXJtaXNzaW9uIiwiQ2FuVXBkYXRlUGVybWlzc2lvbiIsIkNhbkRlbGV0ZVBlcm1pc3Npb24iLCJDb21tZW50T25MZXNzb25zIiwiQ2FuUmVhZFJvbGUiLCJDYW5DcmVhdGVSb2xlIiwiQ2FuVXBkYXRlUm9sZSIsIkNhbkRlbGV0ZVJvbGUiXSwiZXhwIjoxNzU0ODI2NjQ5LCJpc3MiOiJDb3Vyc2VQbGF0Zm9ybUF1dGgiLCJhdWQiOiJDb3Vyc2VQbGF0Zm9ybVVzZXJzIn0.WpEbIrdZgmTZDWj7tCM9i1kxciRfe3qhDJiKAu0n_LQ
Content-Type: application/json

### 1. Search Users
### 2. Get User by ID
GET http://localhost:5273/api/admin/users/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NSIsImVtYWlsIjoiYWRtaW5AYWRtaW4xLmNvbSIsIm5hbWUiOiIiLCJqdGkiOiIxNGY3NmYzNy1hZmNiLTQ5YmQtODBjYi04NWFlMDE4YzdlZWQiLCJpYXQiOjE3NTQ4MjMwMjMsInBlcm1pc3Npb24iOlsiQ2FuUmVhZFBlcm1pc3Npb24iLCJDYW5DcmVhdGVQZXJtaXNzaW9uIiwiQ2FuVXBkYXRlUGVybWlzc2lvbiIsIkNhbkRlbGV0ZVBlcm1pc3Npb24iLCJDb21tZW50T25MZXNzb25zIiwiQ2FuUmVhZFJvbGUiLCJDYW5DcmVhdGVSb2xlIiwiQ2FuVXBkYXRlUm9sZSIsIkNhbkRlbGV0ZVJvbGUiXSwiZXhwIjoxNzU0ODI2NjQ5LCJpc3MiOiJDb3Vyc2VQbGF0Zm9ybUF1dGgiLCJhdWQiOiJDb3Vyc2VQbGF0Zm9ybVVzZXJzIn0.WpEbIrdZgmTZDWj7tCM9i1kxciRfe3qhDJiKAu0n_LQ
Content-Type: application/json

### 3. Get User Permissions
GET http://localhost:5273/api/admin/users/1/permissions HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NSIsImVtYWlsIjoiYWRtaW5AYWRtaW4xLmNvbSIsIm5hbWUiOiIiLCJqdGkiOiIxNGY3NmYzNy1hZmNiLTQ5YmQtODBjYi04NWFlMDE4YzdlZWQiLCJpYXQiOjE3NTQ4MjMwMjMsInBlcm1pc3Npb24iOlsiQ2FuUmVhZFBlcm1pc3Npb24iLCJDYW5DcmVhdGVQZXJtaXNzaW9uIiwiQ2FuVXBkYXRlUGVybWlzc2lvbiIsIkNhbkRlbGV0ZVBlcm1pc3Npb24iLCJDb21tZW50T25MZXNzb25zIiwiQ2FuUmVhZFJvbGUiLCJDYW5DcmVhdGVSb2xlIiwiQ2FuVXBkYXRlUm9sZSIsIkNhbkRlbGV0ZVJvbGUiXSwiZXhwIjoxNzU0ODI2NjQ5LCJpc3MiOiJDb3Vyc2VQbGF0Zm9ybUF1dGgiLCJhdWQiOiJDb3Vyc2VQbGF0Zm9ybVVzZXJzIn0.WpEbIrdZgmTZDWj7tCM9i1kxciRfe3qhDJiKAu0n_LQ
Content-Type: application/json

### 4. Assign User Permission
POST http://localhost:5273/api/admin/users/1/permissions/45 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NSIsImVtYWlsIjoiYWRtaW5AYWRtaW4xLmNvbSIsIm5hbWUiOiIiLCJqdGkiOiIxNGY3NmYzNy1hZmNiLTQ5YmQtODBjYi04NWFlMDE4YzdlZWQiLCJpYXQiOjE3NTQ4MjMwMjMsInBlcm1pc3Npb24iOlsiQ2FuUmVhZFBlcm1pc3Npb24iLCJDYW5DcmVhdGVQZXJtaXNzaW9uIiwiQ2FuVXBkYXRlUGVybWlzc2lvbiIsIkNhbkRlbGV0ZVBlcm1pc3Npb24iLCJDb21tZW50T25MZXNzb25zIiwiQ2FuUmVhZFJvbGUiLCJDYW5DcmVhdGVSb2xlIiwiQ2FuVXBkYXRlUm9sZSIsIkNhbkRlbGV0ZVJvbGUiXSwiZXhwIjoxNzU0ODI2NjQ5LCJpc3MiOiJDb3Vyc2VQbGF0Zm9ybUF1dGgiLCJhdWQiOiJDb3Vyc2VQbGF0Zm9ybVVzZXJzIn0.WpEbIrdZgmTZDWj7tCM9i1kxciRfe3qhDJiKAu0n_LQ
Content-Type: application/json

### 5. Remove User Permission
DELETE http://localhost:5273/api/admin/users/1/permissions/45 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NSIsImVtYWlsIjoiYWRtaW5AYWRtaW4xLmNvbSIsIm5hbWUiOiIiLCJqdGkiOiIxNGY3NmYzNy1hZmNiLTQ5YmQtODBjYi04NWFlMDE4YzdlZWQiLCJpYXQiOjE3NTQ4MjMwMjMsInBlcm1pc3Npb24iOlsiQ2FuUmVhZFBlcm1pc3Npb24iLCJDYW5DcmVhdGVQZXJtaXNzaW9uIiwiQ2FuVXBkYXRlUGVybWlzc2lvbiIsIkNhbkRlbGV0ZVBlcm1pc3Npb24iLCJDb21tZW50T25MZXNzb25zIiwiQ2FuUmVhZFJvbGUiLCJDYW5DcmVhdGVSb2xlIiwiQ2FuVXBkYXRlUm9sZSIsIkNhbkRlbGV0ZVJvbGUiXSwiZXhwIjoxNzU0ODI2NjQ5LCJpc3MiOiJDb3Vyc2VQbGF0Zm9ybUF1dGgiLCJhdWQiOiJDb3Vyc2VQbGF0Zm9ybVVzZXJzIn0.WpEbIrdZgmTZDWj7tCM9i1kxciRfe3qhDJiKAu0n_LQ
Content-Type: application/json

### 6. Get User Roles
GET http://localhost:5273/api/admin/users/1/roles HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NSIsImVtYWlsIjoiYWRtaW5AYWRtaW4xLmNvbSIsIm5hbWUiOiIiLCJqdGkiOiIxNGY3NmYzNy1hZmNiLTQ5YmQtODBjYi04NWFlMDE4YzdlZWQiLCJpYXQiOjE3NTQ4MjMwMjMsInBlcm1pc3Npb24iOlsiQ2FuUmVhZFBlcm1pc3Npb24iLCJDYW5DcmVhdGVQZXJtaXNzaW9uIiwiQ2FuVXBkYXRlUGVybWlzc2lvbiIsIkNhbkRlbGV0ZVBlcm1pc3Npb24iLCJDb21tZW50T25MZXNzb25zIiwiQ2FuUmVhZFJvbGUiLCJDYW5DcmVhdGVSb2xlIiwiQ2FuVXBkYXRlUm9sZSIsIkNhbkRlbGV0ZVJvbGUiXSwiZXhwIjoxNzU0ODI2NjQ5LCJpc3MiOiJDb3Vyc2VQbGF0Zm9ybUF1dGgiLCJhdWQiOiJDb3Vyc2VQbGF0Zm9ybVVzZXJzIn0.WpEbIrdZgmTZDWj7tCM9i1kxciRfe3qhDJiKAu0n_LQ
Content-Type: application/json

### 7. Assign User Role
POST http://localhost:5273/api/admin/users/1/roles/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NSIsImVtYWlsIjoiYWRtaW5AYWRtaW4xLmNvbSIsIm5hbWUiOiIiLCJqdGkiOiIxNGY3NmYzNy1hZmNiLTQ5YmQtODBjYi04NWFlMDE4YzdlZWQiLCJpYXQiOjE3NTQ4MjMwMjMsInBlcm1pc3Npb24iOlsiQ2FuUmVhZFBlcm1pc3Npb24iLCJDYW5DcmVhdGVQZXJtaXNzaW9uIiwiQ2FuVXBkYXRlUGVybWlzc2lvbiIsIkNhbkRlbGV0ZVBlcm1pc3Npb24iLCJDb21tZW50T25MZXNzb25zIiwiQ2FuUmVhZFJvbGUiLCJDYW5DcmVhdGVSb2xlIiwiQ2FuVXBkYXRlUm9sZSIsIkNhbkRlbGV0ZVJvbGUiXSwiZXhwIjoxNzU0ODI2NjQ5LCJpc3MiOiJDb3Vyc2VQbGF0Zm9ybUF1dGgiLCJhdWQiOiJDb3Vyc2VQbGF0Zm9ybVVzZXJzIn0.WpEbIrdZgmTZDWj7tCM9i1kxciRfe3qhDJiKAu0n_LQ
Content-Type: application/json

### 8. Remove User Role
DELETE http://localhost:5273/api/admin/users/1/roles/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NSIsImVtYWlsIjoiYWRtaW5AYWRtaW4xLmNvbSIsIm5hbWUiOiIiLCJqdGkiOiIxNGY3NmYzNy1hZmNiLTQ5YmQtODBjYi04NWFlMDE4YzdlZWQiLCJpYXQiOjE3NTQ4MjMwMjMsInBlcm1pc3Npb24iOlsiQ2FuUmVhZFBlcm1pc3Npb24iLCJDYW5DcmVhdGVQZXJtaXNzaW9uIiwiQ2FuVXBkYXRlUGVybWlzc2lvbiIsIkNhbkRlbGV0ZVBlcm1pc3Npb24iLCJDb21tZW50T25MZXNzb25zIiwiQ2FuUmVhZFJvbGUiLCJDYW5DcmVhdGVSb2xlIiwiQ2FuVXBkYXRlUm9sZSIsIkNhbkRlbGV0ZVJvbGUiXSwiZXhwIjoxNzU0ODI2NjQ5LCJpc3MiOiJDb3Vyc2VQbGF0Zm9ybUF1dGgiLCJhdWQiOiJDb3Vyc2VQbGF0Zm9ybVVzZXJzIn0.WpEbIrdZgmTZDWj7tCM9i1kxciRfe3qhDJiKAu0n_LQ
Content-Type: application/json
