### 1. Create new permission
POST http://localhost:5273/api/admin/permissions
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NSIsImVtYWlsIjoiYWRtaW5AYWRtaW4xLmNvbSIsIm5hbWUiOiIiLCJqdGkiOiIyMGRlMmQ3NC1hMWNiLTQwNTMtYmU1My05ZmQ5M2I0NDM0ZGYiLCJpYXQiOjE3NTQ4MTk5ODUsImV4cCI6MTc1NDgyMzU4NSwiaXNzIjoiQ291cnNlUGxhdGZvcm1BdXRoIiwiYXVkIjoiQ291cnNlUGxhdGZvcm1Vc2VycyJ9.1Zk92iyKPn-yWItJ1y-8UmP8GgoKXZ6AaxT-8nIupyU


{
  "name": "testPERmission"
}

### 2. Get all permissions
GET http://localhost:5273/api/admin/permissions
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NSIsImVtYWlsIjoiYWRtaW5AYWRtaW4xLmNvbSIsIm5hbWUiOiIiLCJqdGkiOiI5ZWQzY2YzMS1kMDY1LTRmMzAtYWRlYy00NmY5OWNjMTkxNzQiLCJpYXQiOjE3NTQ2ODg1MTIsInBlcm1pc3Npb24iOlsiQ2FuUmVhZFBlcm1pc3Npb24iLCJDYW5DcmVhdGVQZXJtaXNzaW9uIiwiQ2FuVXBkYXRlUGVybWlzc2lvbiIsIkNhbkRlbGV0ZVBlcm1pc3Npb24iLCJDb21tZW50T25MZXNzb25zIiwiQ2FuUmVhZFJvbGUiLCJDYW5DcmVhdGVSb2xlIiwiQ2FuVXBkYXRlUm9sZSIsIkNhbkRlbGV0ZVJvbGUiXSwiZXhwIjoxNzU0NjkyMTEyLCJpc3MiOiJDb3Vyc2VQbGF0Zm9ybUF1dGgiLCJhdWQiOiJDb3Vyc2VQbGF0Zm9ybVVzZXJzIn0._ZdbVtD07XSgl-qbCgL56lBJTho-x-TnqTnxsQ1cEC4


### 2. Get all permissions (via query string) ✅ preferred for GET
GET http://localhost:5273/api/admin/permissions?name=cour&pageNumber=1&pageSize=10
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NSIsImVtYWlsIjoiYWRtaW5AYWRtaW4xLmNvbSIsIm5hbWUiOiIiLCJqdGkiOiI5ZWQzY2YzMS1kMDY1LTRmMzAtYWRlYy00NmY5OWNjMTkxNzQiLCJpYXQiOjE3NTQ2ODg1MTIsInBlcm1pc3Npb24iOlsiQ2FuUmVhZFBlcm1pc3Npb24iLCJDYW5DcmVhdGVQZXJtaXNzaW9uIiwiQ2FuVXBkYXRlUGVybWlzc2lvbiIsIkNhbkRlbGV0ZVBlcm1pc3Npb24iLCJDb21tZW50T25MZXNzb25zIiwiQ2FuUmVhZFJvbGUiLCJDYW5DcmVhdGVSb2xlIiwiQ2FuVXBkYXRlUm9sZSIsIkNhbkRlbGV0ZVJvbGUiXSwiZXhwIjoxNzU0NjkyMTEyLCJpc3MiOiJDb3Vyc2VQbGF0Zm9ybUF1dGgiLCJhdWQiOiJDb3Vyc2VQbGF0Zm9ybVVzZXJzIn0._ZdbVtD07XSgl-qbCgL56lBJTho-x-TnqTnxsQ1cEC4


### 4. Get permission by ID
GET http://localhost:5273/api/admin/permissions/10
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NSIsImVtYWlsIjoiYWRtaW5AYWRtaW4xLmNvbSIsIm5hbWUiOiIiLCJqdGkiOiI5ZWQzY2YzMS1kMDY1LTRmMzAtYWRlYy00NmY5OWNjMTkxNzQiLCJpYXQiOjE3NTQ2ODg1MTIsInBlcm1pc3Npb24iOlsiQ2FuUmVhZFBlcm1pc3Npb24iLCJDYW5DcmVhdGVQZXJtaXNzaW9uIiwiQ2FuVXBkYXRlUGVybWlzc2lvbiIsIkNhbkRlbGV0ZVBlcm1pc3Npb24iLCJDb21tZW50T25MZXNzb25zIiwiQ2FuUmVhZFJvbGUiLCJDYW5DcmVhdGVSb2xlIiwiQ2FuVXBkYXRlUm9sZSIsIkNhbkRlbGV0ZVJvbGUiXSwiZXhwIjoxNzU0NjkyMTEyLCJpc3MiOiJDb3Vyc2VQbGF0Zm9ybUF1dGgiLCJhdWQiOiJDb3Vyc2VQbGF0Zm9ybVVzZXJzIn0._ZdbVtD07XSgl-qbCgL56lBJTho-x-TnqTnxsQ1cEC4

### 5. Delete permission by ID
DELETE http://localhost:5273/api/admin/permissions/19
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NSIsImVtYWlsIjoiYWRtaW5AYWRtaW4xLmNvbSIsIm5hbWUiOiIiLCJqdGkiOiI5ZWQzY2YzMS1kMDY1LTRmMzAtYWRlYy00NmY5OWNjMTkxNzQiLCJpYXQiOjE3NTQ2ODg1MTIsInBlcm1pc3Npb24iOlsiQ2FuUmVhZFBlcm1pc3Npb24iLCJDYW5DcmVhdGVQZXJtaXNzaW9uIiwiQ2FuVXBkYXRlUGVybWlzc2lvbiIsIkNhbkRlbGV0ZVBlcm1pc3Npb24iLCJDb21tZW50T25MZXNzb25zIiwiQ2FuUmVhZFJvbGUiLCJDYW5DcmVhdGVSb2xlIiwiQ2FuVXBkYXRlUm9sZSIsIkNhbkRlbGV0ZVJvbGUiXSwiZXhwIjoxNzU0NjkyMTEyLCJpc3MiOiJDb3Vyc2VQbGF0Zm9ybUF1dGgiLCJhdWQiOiJDb3Vyc2VQbGF0Zm9ybVVzZXJzIn0._ZdbVtD07XSgl-qbCgL56lBJTho-x-TnqTnxsQ1cEC4
