version: "3.8"

services:
  userservice-db-srv:
    image: postgres:16
    container_name: userservice-db
    restart: always
    environment:
      POSTGRES_USER: ${USERSERVICE_DB_USER}
      POSTGRES_PASSWORD: ${USERSERVICE_DB_PASSWORD}
      POSTGRES_DB: ${USERSERVICE_DB_NAME}
    ports:
      - "${USERSERVICE_DB_PORT}:5432"
    volumes:
      - userservice-data:/var/lib/postgresql/data

  userservice-srv:
    build:
      context: ../
      dockerfile: UserService/Dockerfile
    container_name: userservice
    depends_on:
      - userservice-db-srv
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      CONNECTIONSTRINGS__USERSDB: Host=userservice-db-srv;Port=5432;Database=${USERSERVICE_DB_NAME};Username=${USERSERVICE_DB_USER};Password=${USERSERVICE_DB_PASSWORD}
    ports:
      - "${USERSERVICE_PORT}:5125"

  authservice-db-srv:
    image: postgres:16
    container_name: authservice-db
    restart: always
    environment:
      POSTGRES_USER: ${AUTHSERVICE_DB_USER}
      POSTGRES_PASSWORD: ${AUTHSERVICE_DB_PASSWORD}
      POSTGRES_DB: ${AUTHSERVICE_DB_NAME}
    ports:
      - "${AUTHSERVICE_DB_PORT}:5432"
    volumes:
      - authservice-data:/var/lib/postgresql/data

  courseservice-db-srv:
    image: postgres:16
    container_name: courseservice-db
    restart: always
    environment:
      POSTGRES_USER: ${COURSESERVICE_DB_USER}
      POSTGRES_PASSWORD: ${COURSESERVICE_DB_PASSWORD}
      POSTGRES_DB: ${COURSESERVICE_DB_NAME}
    ports:
      - "${COURSESERVICE_DB_PORT}:5432"
    volumes:
      - courseservice-data:/var/lib/postgresql/data

  enrollmentservice-db-srv:
    image: postgres:16
    container_name: enrollmentservice-db
    restart: always
    environment:
      POSTGRES_USER: ${ENROLLMENTSERVICE_DB_USER}
      POSTGRES_PASSWORD: ${ENROLLMENTSERVICE_DB_PASSWORD}
      POSTGRES_DB: ${ENROLLMENTSERVICE_DB_NAME}
    ports:
      - "${ENROLLMENTSERVICE_DB_PORT}:5432"
    volumes:
      - enrollmentservice-data:/var/lib/postgresql/data

  orderservice-db-srv:
    image: postgres:16
    container_name: orderservice-db
    restart: always
    environment:
      POSTGRES_USER: ${ORDERSERVICE_DB_USER}
      POSTGRES_PASSWORD: ${ORDERSERVICE_DB_PASSWORD}
      POSTGRES_DB: ${ORDERSERVICE_DB_NAME}
    ports:
      - "${ORDERSERVICE_DB_PORT}:5432"
    volumes:
      - orderservice-data:/var/lib/postgresql/data

volumes:
  userservice-data:
  authservice-data:
  courseservice-data:
  enrollmentservice-data:
  orderservice-data:
