### 1. Create new permission
POST http://localhost:5273/api/admin/permissions
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NSIsImVtYWlsIjoiYWRtaW5AYWRtaW4xLmNvbSIsIm5hbWUiOiIiLCJqdGkiOiI2OWQ0Y2Y3My1kMzQyLTQ5MDUtYjQ5Yi0yODA1OTY1MjVhZjUiLCJpYXQiOjE3NTQ4MjU4NTIsInBlcm1pc3Npb24iOlsiQ2FuUmVhZFBlcm1pc3Npb24iLCJDYW5DcmVhdGVQZXJtaXNzaW9uIiwiQ2FuVXBkYXRlUGVybWlzc2lvbiIsIkNhbkRlbGV0ZVBlcm1pc3Npb24iLCJDb21tZW50T25MZXNzb25zIiwiQ2FuUmVhZFJvbGUiLCJDYW5DcmVhdGVSb2xlIiwiQ2FuVXBkYXRlUm9sZSIsIkNhbkRlbGV0ZVJvbGUiXSwiZXhwIjoxNzU0ODI5NDUyLCJpc3MiOiJDb3Vyc2VQbGF0Zm9ybUF1dGgiLCJhdWQiOiJDb3Vyc2VQbGF0Zm9ybVVzZXJzIn0.Ah3WcvK_ps371lxs08MfztlYxFtkzoXFOiUanSbrLMk


{
  "name": "CanUpdateAuthUsers"
}

### 2. Get all permissions
GET http://localhost:5273/api/admin/permissions
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NSIsImVtYWlsIjoiYWRtaW5AYWRtaW4xLmNvbSIsIm5hbWUiOiIiLCJqdGkiOiJkOTk4MmViOC1kZDVjLTQyNWEtYTA5NS0xNGJmYmZjNTdjOTciLCJpYXQiOjE3NTQ4MjU3NzIsInBlcm1pc3Npb24iOlsiQ2FuUmVhZFBlcm1pc3Npb24iLCJDYW5DcmVhdGVQZXJtaXNzaW9uIiwiQ2FuVXBkYXRlUGVybWlzc2lvbiIsIkNhbkRlbGV0ZVBlcm1pc3Npb24iLCJDb21tZW50T25MZXNzb25zIiwiQ2FuUmVhZFJvbGUiLCJDYW5DcmVhdGVSb2xlIiwiQ2FuVXBkYXRlUm9sZSIsIkNhbkRlbGV0ZVJvbGUiXSwiZXhwIjoxNzU0ODI5MzcyLCJpc3MiOiJDb3Vyc2VQbGF0Zm9ybUF1dGgiLCJhdWQiOiJDb3Vyc2VQbGF0Zm9ybVVzZXJzIn0.333mqMETUYXCf7isTyFJ23826OK9nO0PWe1Gb-lDvRc


### 2. Get all permissions (via query string) ✅ preferred for GET
GET http://localhost:5273/api/admin/permissions?name=cour&pageNumber=1&pageSize=10
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NSIsImVtYWlsIjoiYWRtaW5AYWRtaW4xLmNvbSIsIm5hbWUiOiIiLCJqdGkiOiJkOTk4MmViOC1kZDVjLTQyNWEtYTA5NS0xNGJmYmZjNTdjOTciLCJpYXQiOjE3NTQ4MjU3NzIsInBlcm1pc3Npb24iOlsiQ2FuUmVhZFBlcm1pc3Npb24iLCJDYW5DcmVhdGVQZXJtaXNzaW9uIiwiQ2FuVXBkYXRlUGVybWlzc2lvbiIsIkNhbkRlbGV0ZVBlcm1pc3Npb24iLCJDb21tZW50T25MZXNzb25zIiwiQ2FuUmVhZFJvbGUiLCJDYW5DcmVhdGVSb2xlIiwiQ2FuVXBkYXRlUm9sZSIsIkNhbkRlbGV0ZVJvbGUiXSwiZXhwIjoxNzU0ODI5MzcyLCJpc3MiOiJDb3Vyc2VQbGF0Zm9ybUF1dGgiLCJhdWQiOiJDb3Vyc2VQbGF0Zm9ybVVzZXJzIn0.333mqMETUYXCf7isTyFJ23826OK9nO0PWe1Gb-lDvRc


### 4. Get permission by ID
GET http://localhost:5273/api/admin/permissions/10
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NSIsImVtYWlsIjoiYWRtaW5AYWRtaW4xLmNvbSIsIm5hbWUiOiIiLCJqdGkiOiJkOTk4MmViOC1kZDVjLTQyNWEtYTA5NS0xNGJmYmZjNTdjOTciLCJpYXQiOjE3NTQ4MjU3NzIsInBlcm1pc3Npb24iOlsiQ2FuUmVhZFBlcm1pc3Npb24iLCJDYW5DcmVhdGVQZXJtaXNzaW9uIiwiQ2FuVXBkYXRlUGVybWlzc2lvbiIsIkNhbkRlbGV0ZVBlcm1pc3Npb24iLCJDb21tZW50T25MZXNzb25zIiwiQ2FuUmVhZFJvbGUiLCJDYW5DcmVhdGVSb2xlIiwiQ2FuVXBkYXRlUm9sZSIsIkNhbkRlbGV0ZVJvbGUiXSwiZXhwIjoxNzU0ODI5MzcyLCJpc3MiOiJDb3Vyc2VQbGF0Zm9ybUF1dGgiLCJhdWQiOiJDb3Vyc2VQbGF0Zm9ybVVzZXJzIn0.333mqMETUYXCf7isTyFJ23826OK9nO0PWe1Gb-lDvRc

### 5. Delete permission by ID
DELETE http://localhost:5273/api/admin/permissions/19
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NSIsImVtYWlsIjoiYWRtaW5AYWRtaW4xLmNvbSIsIm5hbWUiOiIiLCJqdGkiOiJkOTk4MmViOC1kZDVjLTQyNWEtYTA5NS0xNGJmYmZjNTdjOTciLCJpYXQiOjE3NTQ4MjU3NzIsInBlcm1pc3Npb24iOlsiQ2FuUmVhZFBlcm1pc3Npb24iLCJDYW5DcmVhdGVQZXJtaXNzaW9uIiwiQ2FuVXBkYXRlUGVybWlzc2lvbiIsIkNhbkRlbGV0ZVBlcm1pc3Npb24iLCJDb21tZW50T25MZXNzb25zIiwiQ2FuUmVhZFJvbGUiLCJDYW5DcmVhdGVSb2xlIiwiQ2FuVXBkYXRlUm9sZSIsIkNhbkRlbGV0ZVJvbGUiXSwiZXhwIjoxNzU0ODI5MzcyLCJpc3MiOiJDb3Vyc2VQbGF0Zm9ybUF1dGgiLCJhdWQiOiJDb3Vyc2VQbGF0Zm9ybVVzZXJzIn0.333mqMETUYXCf7isTyFJ23826OK9nO0PWe1Gb-lDvRc
